import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import Footer from "@/ui/Footer";
import MetaProvider from "@/contexts/MetaContext";
import { ReactLenis } from "@/utils/lenis";

const nunito = Nunito({
  subsets: ["latin"], // or ["latin-ext"] if needed
  variable: "--font-nunito", // optional: creates a CSS variable
  weight: ["400", "600", "700"], // pick the weights you need
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} antialiased bg-black relative`}>
        <ReactLenis root>
          <QueryProvider>
            <MetaProvider>
              <>
                {children}
                <Footer />
              </>
            </MetaProvider>
          </QueryProvider>
        </ReactLenis>
      </body>
    </html>
  );
}
