export const appRoutes = {
  home: "/",
  whoWeAre: "/who-we-are",
  whatWeDo: "/what-we-do",
  career: "/career",
  insights: "/insights",
  platforms: "/platforms",
  aivyChat: "/aivy-chat",
  qnlnewsletter: "/QNL-Newsletter",
  contactus: "/contact-us",
  qnlbpm: "/QNL-BPM",
  harmony: "/harmony",
  privacypolicy: "/privacy-policy",
  termsandconditions: "/terms-&-conditions",
  cookiepolicy: "/cookie-policy",
  locations: "/locations",
  sitemap: "/sitemap",
  csrandsustainability: "CSR-&-Sustainability",
  openroles: "/career/open-roles",
  joinus: "/join-us",
  applynow: "/career/apply-now",
  caseStudy: "/case-study",
  learnMore: "/learn-more",
};
